CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author VARCHAR(255) NOT NULL,
    create_time TIMESTAMP NOT NULL
);

CREATE INDEX idx_posts_create_time ON posts (create_time DESC);

